#!/bin/bash
sudo true

echo "Get the current theme name"
echo " Usage: gdm3-patch"
echo
echo "Set a theme and use its gresource file as it"
echo " Usage: gdm3-patch <theme path>"
echo
echo "Set a theme and compile-it with <css file> as GDM3 theme"
echo " Usage: gdm3-patch <theme path> <css file>"
echo " (Usualy, <css file> is 'gdm3.css' or 'gnome-shell.css')"
echo
echo

if [ "$#" == "0" ]
then

	if [ -f "/usr/share/gnome-shell/gdm3/name.txt" ]
	then
		echo "Theme: $(cat /usr/share/gnome-shell/gdm3/name.txt)"
	else
		echo "No third-party theme set, GDM3 uses the default 'gnome-shell-theme.gresource'"
	fi

elif [ "$#" == "1" ] || [ "$#" == "2" ]
then

	if ! [ -d "$1/gnome-shell" ]
	then
		if ! [ -d "$1" ]
		then
			echo "This theme doesn't exists!"
			exit
		else
			echo "This theme doesn't support Gnome Shell!"
			exit
		fi
	fi

	if [ "$#" == "1" ]
	then
		if ! [ -f "$1/gnome-shell/$2/gnome-shell-theme.gresource" ]
		then
			echo "This theme doesn't have a gresource file!"
			echo "Compilation mandatory, you must specify a <css file>"
			exit
		fi
	else
		if ! [ -f "$1/gnome-shell/$2" ]
		then
			echo "This theme doesn't have a '$2' file!"
			exit
		fi
	fi

	sudo update-alternatives --remove gdm3-theme.gresource /usr/share/gnome-shell/gdm3/gnome-shell-theme.gresource
	sudo rm -r /usr/share/gnome-shell/gdm3
	sudo cp -r "$1/gnome-shell" /usr/share/gnome-shell/gdm3
	cd /usr/share/gnome-shell/gdm3

	if [ "$#" == "2" ]
	then
		sudo cp "$2" gdm3.css
		echo | sudo tee -a gnome-shell-theme.gresource.xml
		echo "<gresources>" | sudo tee -a gnome-shell-theme.gresource.xml
		echo "  <gresource prefix=\"/org/gnome/shell/theme\">" | sudo tee -a gnome-shell-theme.gresource.xml
		echo "    <file>gdm3.css</file>" | sudo tee -a gnome-shell-theme.gresource.xml
		echo "  </gresource>" | sudo tee -a gnome-shell-theme.gresource.xml
		echo "</gresources>" | sudo tee -a gnome-shell-theme.gresource.xml
		sudo rm gnome-shell-theme.gresource
		sudo glib-compile-resources gnome-shell-theme.gresource.xml
	fi

	echo "$1" | sudo tee -a name.txt
	sudo update-alternatives --install /usr/share/gnome-shell/gdm3-theme.gresource gdm3-theme.gresource /usr/share/gnome-shell/gdm3/gnome-shell-theme.gresource 100
	echo
	echo

	while true
	do
		read -p "Restart GDM3? [Y/n] " yn
		case $yn in
			[Yy]* ) sudo systemctl restart gdm3.service; break;;
			[Nn]* ) break;;
		esac
	done

else

	echo "Syntaxt error!"

fi
