// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 9);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 56362);
user_pref("browser.cache.disk.capacity", 163840);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.ctrlTab.recentlyUsedOrder", false);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 94);
user_pref("browser.newtabpage.activity-stream.feeds.snippets", true);
user_pref("browser.newtabpage.activity-stream.impressionId", "{ed592382-83d5-44dd-bd2e-ee9c0ade8669}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200602222727");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1611842774");
user_pref("browser.startup.homepage", "about:newtab");
user_pref("browser.startup.homepage_override.buildID", "20200602222727");
user_pref("browser.startup.homepage_override.mstone", "77.0.1");
user_pref("browser.tabs.drawInTitlebar", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"chrome-gnome-shell_gnome_org-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":4}");
user_pref("browser.urlbar.placeholderName", "Yahoo!");
user_pref("distribution.iniFile.exists.appversion", "77.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "77.0.1");
user_pref("extensions.lastPlatformVersion", "77.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.ui.theme.hidden", false);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.chrome-gnome-shell@gnome.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"693c316f-549f-4984-a5e3-66e12fa26de7\",\"formautofill@mozilla.org\":\"f36a137c-82f3-4a28-8e41-ed09724add47\",\"screenshots@mozilla.org\":\"0dd01771-96a1-42e0-a65b-6ad7f449672e\",\"webcompat-reporter@mozilla.org\":\"bb994442-59e3-4f85-ae6a-8e27fcd063f8\",\"webcompat@mozilla.org\":\"55daddc0-1f98-4f96-949d-8d12a73f7235\",\"default-theme@mozilla.org\":\"b6d30a55-71e2-4358-9d9a-e084924dc46b\",\"yahoo@search.mozilla.org\":\"ded89f81-63dc-4335-b95e-b4150ccb003f\",\"startpage@search.mozilla.org\":\"2ee8cdf9-12bf-4bf1-b9e4-7120a9215aec\",\"duckduckgo@search.mozilla.org\":\"fc4ffc3a-4d93-48fd-a557-db95b7e8bf58\",\"twitter@search.mozilla.org\":\"5dc41d15-f549-4b34-befe-f4375ba06834\",\"wikipedia@search.mozilla.org\":\"d59ea029-c498-455d-8b9c-44b0f08e3a8b\",\"firefox-compact-dark@mozilla.org\":\"ab45f65b-98e7-46ec-be22-cef56e64fd8b\",\"chrome-gnome-shell@gnome.org\":\"afe32cdf-7e0a-49e9-a768-d6df9bfdcb48\",\"firefox-compact-light@mozilla.org\":\"732d846a-e1c2-406a-a717-52fd401242ce\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 22606);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("security.remote_settings.crlite_filters.checked", 1610761548);
user_pref("security.remote_settings.intermediates.checked", 1610761548);
user_pref("security.sandbox.content.tempDirSuffix", "cb4ef9de-f27c-4b0f-b39f-112dcc0614c8");
user_pref("security.sandbox.plugin.tempDirSuffix", "d961e03f-0ad9-4078-b001-aa86aed930a4");
user_pref("services.blocklist.addons.checked", 1611845771);
user_pref("services.blocklist.gfx.checked", 1611845771);
user_pref("services.blocklist.pinning.checked", 1610761548);
user_pref("services.blocklist.plugins.checked", 1611845771);
user_pref("services.settings.clock_skew_seconds", -4536);
user_pref("services.settings.security.onecrl.checked", 1610761548);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("svg.context-properties.content.enabled", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
