// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1611843982);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1611844087);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1611843589);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1611843825);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1611844341);
user_pref("browser.cache.disk.amount_written", 1039);
user_pref("browser.cache.disk.capacity", 163840);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Fri, 22 Jan 2021 23:33:01 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1611843982);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200629235513");
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"8633d473-19a3-4d02-bce8-c3845e2c39dd\",\"default-theme@mozilla.org\":\"ecbb3cf8-c0dc-4a27-8c87-fc20e329acc4\",\"google@search.mozilla.org\":\"5e17d31b-fd7a-4305-8dbb-acc238ee7515\",\"amazon@search.mozilla.org\":\"e61ae646-2a8f-4075-8c23-edff745ad6c7\",\"bing@search.mozilla.org\":\"f09572aa-97d0-4a31-9b79-61535b44e638\",\"ddg@search.mozilla.org\":\"e9890eea-0a83-4f53-b9d7-ce23e3708989\",\"twitter@search.mozilla.org\":\"4684841c-ef21-4b81-a7f0-30fa3a981064\",\"wikipedia@search.mozilla.org\":\"2eec7f1d-1222-4b26-84b4-8644037b3858\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.pane_config.dynamic", 2);
user_pref("mail.preferences.advanced.selectedTabIndex", 0);
user_pref("mail.preferences.chat.selectedTabIndex", 0);
user_pref("mail.preferences.compose.selectedTabIndex", 0);
user_pref("mail.preferences.display.selectedTabIndex", 0);
user_pref("mail.preferences.security.selectedTabIndex", 0);
user_pref("mail.spam.version", 1);
user_pref("mail.tabs.drawInTitlebar", true);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "7bf40985-00b9-446b-8a27-b41b8c19c20");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("places.history.expiration.transient_current_max_pages", 20510);
user_pref("security.sandbox.plugin.tempDirSuffix", "6583ae36-f474-469a-b32a-ffa514c066f3");
user_pref("services.blocklist.pinning.checked", 1611846820);
user_pref("services.settings.clock_skew_seconds", -2996);
user_pref("services.settings.last_etag", "\"1611842278578\"");
user_pref("services.settings.last_update_seconds", 1611846820);
user_pref("services.settings.main.hijack-blocklists.last_check", 1611846820);
user_pref("services.settings.main.language-dictionaries.last_check", 1611846820);
user_pref("services.settings.main.sites-classification.last_check", 1611846820);
user_pref("services.settings.security.onecrl.checked", 1611846820);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.telemetry.cachedClientID", "6ac14ff1-2ed8-4935-8476-ba9d06808218");
user_pref("toolkit.telemetry.prompted", 2);
